#! /bin/bash
echo "Enter your sweet name"
read uname
echo "Enter your password"
read password
echo "Enter your age"
read age
if [[ ($uname == "Narayana" && $password == "password" && $age == "25") ]] ; then
echo "valid user"
else
echo "Invalid user"
fi

========================================================================


#! /bin/bash
echo "Enter your lucky number"
read n
if [[ ($n -eq 100) ]] ;
then
echo "you got 1st prize"
elif [[ ($n -eq 50) ]] ;
then
echo "you got 2nd prize" 
elif [[ ($n -eq 20) ]] ;
then
echo "you got 3rd prize" 
else 
echo "sorry try again latter"
fi

=============================================================================




