#! /bin/bash
echo "Enter your sweet name"
read uname
echo "Enter your password"
read password
echo "Enter your age"
read age
if [[ ($uname == "Narayana" && $password == "password" && $age == "25") ]] ; then
echo "valid user"
else
echo "Invalid user"
fi

========================================================================
